from __future__ import annotations

from collections.abc import Mapping
from datetime import datetime, timedelta
from typing import Any, Protocol

from starlette.websockets import WebSocket

from app.domain.chat.models import ChatHistoryEntry, ChatSession


class PermissionGate(Protocol):
    async def allow_anonymous_chat(self, session_id: str) -> bool: ...


class FeatureFlagEvaluator(Protocol):
    async def is_enabled(self, key: str, *, session_id: str | None = None) -> bool: ...


class ModerationGateway(Protocol):
    async def normalize_profile_name(self, name: str, *, session_id: str) -> str: ...

    async def normalize_message(self, message: str, *, session_id: str) -> str: ...


class AuditSink(Protocol):
    async def record(self, event: str, payload: Mapping[str, Any]) -> None: ...


class EventBus(Protocol):
    async def publish(self, topic: str, payload: Mapping[str, Any]) -> None: ...


class JobDispatcher(Protocol):
    async def dispatch(self, job_name: str, payload: Mapping[str, Any]) -> None: ...


class ConnectionHub(Protocol):
    def register(self, session_id: str, websocket: WebSocket) -> WebSocket | None: ...

    def unregister(self, session_id: str) -> WebSocket | None: ...

    def get(self, session_id: str) -> WebSocket | None: ...

    def has(self, session_id: str) -> bool: ...

    def active_count(self) -> int: ...


class SessionRepository(Protocol):
    async def prepare_for_startup(self, reconnect_window: timedelta) -> None: ...

    async def load_or_create_session(self, session_id: str) -> ChatSession: ...

    async def load_session(self, session_id: str, *, include_history: bool = False) -> ChatSession | None: ...

    async def save_session(self, session: ChatSession) -> None: ...

    async def delete_session(self, session_id: str) -> None: ...

    async def list_expired_session_ids(self, now: datetime) -> list[str]: ...

    async def enqueue_waiting(self, session_id: str) -> None: ...

    async def enqueue_waiting_front(self, session_id: str) -> None: ...

    async def pop_waiting(self) -> str | None: ...

    async def remove_from_waiting_queue(self, session_id: str) -> None: ...

    async def queue_size(self) -> int: ...

    async def append_history(self, session_id: str, entry: ChatHistoryEntry) -> None: ...

    async def load_recent_history(self, session_id: str) -> list[ChatHistoryEntry]: ...


class PresenceRepository(Protocol):
    async def reset_online(self) -> None: ...

    async def mark_online(self, session_id: str) -> bool: ...

    async def mark_offline(self, session_id: str) -> bool: ...

    async def is_online(self, session_id: str) -> bool: ...

    async def online_count(self) -> int: ...


class ReadinessProbe(Protocol):
    async def ping(self) -> None: ...
